import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar1 } from "@/components/navbar";
// import { Waitlist1 } from "@/components/";
import { BackgroundLines } from "@/components/background-lines";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="mx-auto container z-9999">
          <Navbar1 />
        </nav>
        <main>{children}</main>
        <div className="absolute inset-0 z-[-1]">
          <BackgroundLines />
        </div>
        <Toaster />
      </body>
    </html>
  );
}
